FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY ["TableFlow.Api/TableFlow.Api.csproj", "TableFlow.Api/"]
RUN dotnet restore "TableFlow.Api/TableFlow.Api.csproj"

COPY . .
RUN dotnet publish "TableFlow.Api/TableFlow.Api.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final
WORKDIR /app
COPY --from=build /app/publish .
EXPOSE 8080
ENV ASPNETCORE_HTTP_PORTS=8080
ENTRYPOINT ["dotnet", "TableFlow.Api.dll"]
